-- Barthel indeksi değerlendirme tarihçesi
CREATE TABLE IF NOT EXISTS `esh_hasta_barthel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kurum_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `hasta_id` INT UNSIGNED NOT NULL,
  `degerlendirme_tarihi` DATE NOT NULL,
  `barbeslenme` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `barbanyo` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `barbakim` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `bargiyinme` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `barbarsak` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `barmesane` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `bartuvalet` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `bartransfer` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `barmobilite` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `barmerdiven` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `toplam_skor` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `bagimlilik_duzeyi` VARCHAR(32) NOT NULL DEFAULT '',
  `notlar` TEXT DEFAULT NULL,
  `kaydeden_id` INT UNSIGNED DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_barthel_hasta` (`hasta_id`),
  KEY `idx_barthel_tarih` (`degerlendirme_tarihi`),
  KEY `idx_barthel_kurum` (`kurum_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;
