CREATE TABLE IF NOT EXISTS `esh_portal_appointment_requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hasta_id` INT UNSIGNED NOT NULL,
  `kurum_id` INT UNSIGNED NOT NULL,
  `uhds_id` INT UNSIGNED NOT NULL,
  `talep_tarihi` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mevcut_tarih` DATE NOT NULL,
  `talep_tarih` DATE NOT NULL,
  `talep_zaman` TINYINT NULL DEFAULT NULL COMMENT '0 sabah 1 ogle 2 aksam',
  `neden` VARCHAR(500) NOT NULL,
  `durum` VARCHAR(20) NOT NULL DEFAULT 'queued',
  `durum_notu` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_portal_req_hasta` (`hasta_id`),
  KEY `idx_portal_req_kurum` (`kurum_id`),
  KEY `idx_portal_req_durum` (`durum`),
  KEY `idx_portal_req_uhds` (`uhds_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;
