<?php
/**
 * Evde sağlık odaklı ICD-10-TR top 300 tanı adayları.
 * Kaynak: Türkiye ESH literatürü + birinci basamak sıklık verileri (ICD-10-TR adları).
 *
 * @return list<array{icd:string,hastalikadi:string,cat?:int}>
 */
function evde_saglik_icd10_candidates(): array
{
    return [
        // --- Kardiyovasküler (I) — evde sağlıkta en sık ---
        ['icd' => 'I10', 'hastalikadi' => 'Esansiyel (primer) hipertansiyon'],
        ['icd' => 'I11.0', 'hastalikadi' => 'Hipertansif kalp hastalığı, kalp yetmezliği ile'],
        ['icd' => 'I11.9', 'hastalikadi' => 'Hipertansif kalp hastalığı, tanımlanmamış'],
        ['icd' => 'I12.0', 'hastalikadi' => 'Hipertansif böbrek hastalığı, böbrek yetmezliği ile'],
        ['icd' => 'I12.9', 'hastalikadi' => 'Hipertansif böbrek hastalığı, tanımlanmamış'],
        ['icd' => 'I13.0', 'hastalikadi' => 'Hipertansif kalp ve böbrek hastalığı, kalp yetmezliği ile'],
        ['icd' => 'I13.1', 'hastalikadi' => 'Hipertansif kalp ve böbrek hastalığı, böbrek yetmezliği ile'],
        ['icd' => 'I13.2', 'hastalikadi' => 'Hipertansif kalp ve böbrek hastalığı, kalp ve böbrek yetmezliği ile'],
        ['icd' => 'I13.9', 'hastalikadi' => 'Hipertansif kalp ve böbrek hastalığı, tanımlanmamış'],
        ['icd' => 'I15.0', 'hastalikadi' => 'Renovasküler hipertansiyon'],
        ['icd' => 'I20.0', 'hastalikadi' => 'Kararsız angina'],
        ['icd' => 'I20.9', 'hastalikadi' => 'Angina pektoris, tanımlanmamış'],
        ['icd' => 'I21.0', 'hastalikadi' => 'Akut transmural miyokard infarktüsü, ön duvar'],
        ['icd' => 'I21.1', 'hastalikadi' => 'Akut transmural miyokard infarktüsü, alt duvar'],
        ['icd' => 'I21.2', 'hastalikadi' => 'Akut transmural miyokard infarktüsü, diğer lokalizasyonlar'],
        ['icd' => 'I21.4', 'hastalikadi' => 'Akut subendokardiyal miyokard infarktüsü'],
        ['icd' => 'I21.9', 'hastalikadi' => 'Akut miyokard infarktüsü, tanımlanmamış'],
        ['icd' => 'I24.9', 'hastalikadi' => 'Akut iskemik kalp hastalığı, tanımlanmamış'],
        ['icd' => 'I25.0', 'hastalikadi' => 'Aterosklerotik kardiyovasküler hastalık'],
        ['icd' => 'I25.1', 'hastalikadi' => 'Eski miyokard infarktüsü'],
        ['icd' => 'I25.2', 'hastalikadi' => 'Eski transmural miyokard infarktüsü'],
        ['icd' => 'I25.3', 'hastalikadi' => 'Anevrizma, kalp duvarı'],
        ['icd' => 'I25.5', 'hastalikadi' => 'İskemik kardiyomiyopati'],
        ['icd' => 'I25.6', 'hastalikadi' => 'Asimptomatik miyokard iskemisi'],
        ['icd' => 'I25.9', 'hastalikadi' => 'Kronik iskemik kalp hastalığı, tanımlanmamış'],
        ['icd' => 'I26.9', 'hastalikadi' => 'Akut pulmoner emboli, tanımlanmamış'],
        ['icd' => 'I27.9', 'hastalikadi' => 'Pulmoner kalp hastalığı, tanımlanmamış'],
        ['icd' => 'I31.9', 'hastalikadi' => 'Perikard hastalığı, tanımlanmamış'],
        ['icd' => 'I33.0', 'hastalikadi' => 'Akut ve subakut endokardit'],
        ['icd' => 'I34.0', 'hastalikadi' => 'Mitral (kapak) yetmezliği'],
        ['icd' => 'I34.1', 'hastalikadi' => 'Mitral (kapak) darlığı'],
        ['icd' => 'I34.2', 'hastalikadi' => 'Mitral (kapak) darlığı ve yetmezliği'],
        ['icd' => 'I35.0', 'hastalikadi' => 'Aort (kapak) darlığı'],
        ['icd' => 'I35.1', 'hastalikadi' => 'Aort (kapak) yetmezliği'],
        ['icd' => 'I36.0', 'hastalikadi' => 'Triküspit (kapak) darlığı'],
        ['icd' => 'I36.1', 'hastalikadi' => 'Triküspit (kapak) yetmezliği'],
        ['icd' => 'I42.0', 'hastalikadi' => 'Dilate kardiyomiyopati'],
        ['icd' => 'I42.9', 'hastalikadi' => 'Kardiyomiyopati, tanımlanmamış'],
        ['icd' => 'I44.0', 'hastalikadi' => 'Atriyoventriküler blok, birinci derece'],
        ['icd' => 'I44.1', 'hastalikadi' => 'Atriyoventriküler blok, ikinci derece'],
        ['icd' => 'I44.2', 'hastalikadi' => 'Atriyoventriküler blok, tam'],
        ['icd' => 'I44.7', 'hastalikadi' => 'Sol dal bloğu'],
        ['icd' => 'I47.1', 'hastalikadi' => 'Supraventriküler taşikardi'],
        ['icd' => 'I47.2', 'hastalikadi' => 'Ventriküler taşikardi'],
        ['icd' => 'I48.0', 'hastalikadi' => 'Atriyal fibrilasyon'],
        ['icd' => 'I48.1', 'hastalikadi' => 'Atriyal flutter'],
        ['icd' => 'I48.9', 'hastalikadi' => 'Atriyal fibrilasyon ve flutter, tanımlanmamış'],
        ['icd' => 'I49.0', 'hastalikadi' => 'Ventriküler fibrilasyon ve flutter'],
        ['icd' => 'I49.9', 'hastalikadi' => 'Diğer kardiyak aritmi, tanımlanmamış'],
        ['icd' => 'I50.0', 'hastalikadi' => 'Konjestif kalp yetmezliği'],
        ['icd' => 'I50.1', 'hastalikadi' => 'Sol ventrikül yetmezliği'],
        ['icd' => 'I50.2', 'hastalikadi' => 'Kronik kalp yetmezliği'],
        ['icd' => 'I50.3', 'hastalikadi' => 'Akut kalp yetmezliği'],
        ['icd' => 'I50.9', 'hastalikadi' => 'Kalp yetmezliği, tanımlanmamış'],
        ['icd' => 'I51.6', 'hastalikadi' => 'Kardiyomegali'],
        ['icd' => 'I51.9', 'hastalikadi' => 'Kalp hastalığı, tanımlanmamış'],
        ['icd' => 'I60.9', 'hastalikadi' => 'Subaraknoid hemoraji, tanımlanmamış'],
        ['icd' => 'I61.9', 'hastalikadi' => 'İntraserebral hemoraji, tanımlanmamış'],
        ['icd' => 'I63.0', 'hastalikadi' => 'Serebral enfarktüs, tromboz'],
        ['icd' => 'I63.1', 'hastalikadi' => 'Serebral enfarktüs, emboli'],
        ['icd' => 'I63.3', 'hastalikadi' => 'Serebral enfarktüs, tanımlanmamış'],
        ['icd' => 'I63.5', 'hastalikadi' => 'Serebral enfarktüs, oklüzyon veya stenoz olmayan'],
        ['icd' => 'I63.9', 'hastalikadi' => 'Serebral enfarktüs, tanımlanmamış'],
        ['icd' => 'I64', 'hastalikadi' => 'İnme, tanımlanmamış'],
        ['icd' => 'I67.2', 'hastalikadi' => 'Serebral ateroskleroz'],
        ['icd' => 'I69.0', 'hastalikadi' => 'Serebrovasküler hastalık sonrası hemipleji'],
        ['icd' => 'I69.1', 'hastalikadi' => 'Serebrovasküler hastalık sonrası hemiparezi'],
        ['icd' => 'I69.3', 'hastalikadi' => 'Serebrovasküler hastalık sonrası bilişsel işlev bozukluğu'],
        ['icd' => 'I69.4', 'hastalikadi' => 'Serebrovasküler hastalık sonrası afazi'],
        ['icd' => 'I69.8', 'hastalikadi' => 'Serebrovasküler hastalık sonrası diğer sekel'],
        ['icd' => 'I69.9', 'hastalikadi' => 'Serebrovasküler hastalık sonrası sekel, tanımlanmamış'],
        ['icd' => 'I70.0', 'hastalikadi' => 'Ateroskleroz, aorta'],
        ['icd' => 'I70.2', 'hastalikadi' => 'Ateroskleroz, atardamarlar'],
        ['icd' => 'I70.8', 'hastalikadi' => 'Ateroskleroz, diğer atardamarlar'],
        ['icd' => 'I71.3', 'hastalikadi' => 'Abdominal aort anevrizması, rüptür olmadan'],
        ['icd' => 'I71.9', 'hastalikadi' => 'Aort anevrizması, tanımlanmamış'],
        ['icd' => 'I73.9', 'hastalikadi' => 'Periferik vasküler hastalık, tanımlanmamış'],
        ['icd' => 'I80.1', 'hastalikadi' => 'Femoral ven flebiti ve tromboflebiti'],
        ['icd' => 'I80.2', 'hastalikadi' => 'Diğer derin periferik venlerin derin ven trombozu'],
        ['icd' => 'I80.3', 'hastalikadi' => 'Alt ekstremitelerin derin ven trombozu, tanımlanmamış'],
        ['icd' => 'I83.0', 'hastalikadi' => 'Varisli venler, ülserli alt ekstremite'],
        ['icd' => 'I83.1', 'hastalikadi' => 'Varisli venler, inflamasyonlu alt ekstremite'],
        ['icd' => 'I83.9', 'hastalikadi' => 'Varisli venler alt ekstremite, komplikasyonsuz'],
        ['icd' => 'I87.0', 'hastalikadi' => 'Ven yetmezliği, postflebitik'],
        ['icd' => 'I87.1', 'hastalikadi' => 'Basınç ülseri, venöz'],
        ['icd' => 'I87.2', 'hastalikadi' => 'Ven yetmezliği (kronik) (periferik)'],
        ['icd' => 'I89.0', 'hastalikadi' => 'Lenfödem, herhangi bir bölge'],
        ['icd' => 'I95.0', 'hastalikadi' => 'İdiopatik hipotansiyon'],
        ['icd' => 'I95.1', 'hastalikadi' => 'Ortostatik hipotansiyon'],

        // --- Sinir sistemi (G) ---
        ['icd' => 'G12.2', 'hastalikadi' => 'Motor nöron hastalığı'],
        ['icd' => 'G20', 'hastalikadi' => 'Parkinson hastalığı'],
        ['icd' => 'G21.1', 'hastalikadi' => 'İlaca bağlı parkinsonizm'],
        ['icd' => 'G30.0', 'hastalikadi' => 'Alzheimer hastalığı, erken başlangıçlı'],
        ['icd' => 'G30.1', 'hastalikadi' => 'Alzheimer hastalığı, geç başlangıçlı'],
        ['icd' => 'G30.8', 'hastalikadi' => 'Diğer Alzheimer hastalığı'],
        ['icd' => 'G30.9', 'hastalikadi' => 'Alzheimer hastalığı, tanımlanmamış'],
        ['icd' => 'G31.0', 'hastalikadi' => 'Lokalize beyin atrofisi'],
        ['icd' => 'G31.1', 'hastalikadi' => 'Anterior temporal lobda dejenerasyon'],
        ['icd' => 'G31.8', 'hastalikadi' => 'Diğer belirtilmiş sinir sistemi dejeneratif hastalıkları'],
        ['icd' => 'G31.9', 'hastalikadi' => 'Sinir sistemi dejeneratif hastalığı, tanımlanmamış'],
        ['icd' => 'G35', 'hastalikadi' => 'Multiple skleroz'],
        ['icd' => 'G40.9', 'hastalikadi' => 'Epilepsi, tanımlanmamış'],
        ['icd' => 'G43.9', 'hastalikadi' => 'Migren, tanımlanmamış'],
        ['icd' => 'G45.9', 'hastalikadi' => 'Geçici serebral iskemik atak, tanımlanmamış'],
        ['icd' => 'G47.0', 'hastalikadi' => 'Uykusuzluk'],
        ['icd' => 'G47.3', 'hastalikadi' => 'Uyku apnesi'],
        ['icd' => 'G56.0', 'hastalikadi' => 'Karpal tünel sendromu'],
        ['icd' => 'G57.0', 'hastalikadi' => 'Siyatik sinir lezyonları'],
        ['icd' => 'G62.9', 'hastalikadi' => 'Polinöropati, tanımlanmamış'],
        ['icd' => 'G63', 'hastalikadi' => 'Polinöropati, sistemik hastalıkta'],
        ['icd' => 'G81.0', 'hastalikadi' => 'Hemipleji'],
        ['icd' => 'G81.1', 'hastalikadi' => 'Hemiparezi'],
        ['icd' => 'G82.0', 'hastalikadi' => 'Parapleji'],
        ['icd' => 'G82.1', 'hastalikadi' => 'Paraparezi'],
        ['icd' => 'G82.2', 'hastalikadi' => 'Kuadripleji'],
        ['icd' => 'G82.3', 'hastalikadi' => 'Kuadriparezi'],
        ['icd' => 'G93.1', 'hastalikadi' => 'Anoksik beyin hasarı'],
        ['icd' => 'G93.4', 'hastalikadi' => 'Ensefalopati, tanımlanmamış'],

        // --- Zihinsel ve davranışsal (F) ---
        ['icd' => 'F03', 'hastalikadi' => 'Demans, başka yerde sınıflanmamış hastalıkta'],
        ['icd' => 'F10.2', 'hastalikadi' => 'Alkol bağımlılığı sendromu'],
        ['icd' => 'F20.9', 'hastalikadi' => 'Şizofreni, tanımlanmamış'],
        ['icd' => 'F32.0', 'hastalikadi' => 'Majör depresif bozukluk, hafif epizod'],
        ['icd' => 'F32.1', 'hastalikadi' => 'Majör depresif bozukluk, orta epizod'],
        ['icd' => 'F32.9', 'hastalikadi' => 'Depresif epizod, tanımlanmamış'],
        ['icd' => 'F33.1', 'hastalikadi' => 'Rekürren depresif bozukluk, orta epizod'],
        ['icd' => 'F41.0', 'hastalikadi' => 'Panik bozukluk'],
        ['icd' => 'F41.1', 'hastalikadi' => 'Yaygın anksiyete bozukluğu'],
        ['icd' => 'F41.9', 'hastalikadi' => 'Anksiyete bozukluğu, tanımlanmamış'],
        ['icd' => 'F43.1', 'hastalikadi' => 'Posttravmatik stres bozukluğu'],

        // --- Endokrin / metabolizma (E) ---
        ['icd' => 'E10.9', 'hastalikadi' => 'Tip 1 diyabetes mellitus, komplikasyonsuz'],
        ['icd' => 'E11.0', 'hastalikadi' => 'Tip 2 diyabetes mellitus, ketoasidoz ile'],
        ['icd' => 'E11.2', 'hastalikadi' => 'Tip 2 diyabetes mellitus, böbrek komplikasyonları ile'],
        ['icd' => 'E11.3', 'hastalikadi' => 'Tip 2 diyabetes mellitus, oftalmik komplikasyonlar ile'],
        ['icd' => 'E11.4', 'hastalikadi' => 'Tip 2 diyabetes mellitus, nörolojik komplikasyonlar ile'],
        ['icd' => 'E11.5', 'hastalikadi' => 'Tip 2 diyabetes mellitus, periferik dolaşım komplikasyonları ile'],
        ['icd' => 'E11.6', 'hastalikadi' => 'Tip 2 diyabetes mellitus, diğer belirtilmiş komplikasyonlar ile'],
        ['icd' => 'E11.7', 'hastalikadi' => 'Tip 2 diyabetes mellitus, birden fazla komplikasyon ile'],
        ['icd' => 'E11.8', 'hastalikadi' => 'Tip 2 diyabetes mellitus, komplikasyonlarla'],
        ['icd' => 'E11.9', 'hastalikadi' => 'Tip 2 diyabetes mellitus, komplikasyonsuz'],
        ['icd' => 'E13.9', 'hastalikadi' => 'Diğer belirtilmiş diyabetes mellitus'],
        ['icd' => 'E14.9', 'hastalikadi' => 'Diyabetes mellitus, tanımlanmamış'],
        ['icd' => 'E03.0', 'hastalikadi' => 'Konjenital hipotiroidizm'],
        ['icd' => 'E03.9', 'hastalikadi' => 'Hipotiroidizm, tanımlanmamış'],
        ['icd' => 'E44.0', 'hastalikadi' => 'Orta derecede protein-enerji malnütrisyonu'],
        ['icd' => 'E44.1', 'hastalikadi' => 'Hafif protein-enerji malnütrisyonu'],
        ['icd' => 'E46', 'hastalikadi' => 'Protein-enerji malnütrisyonu, tanımlanmamış'],
        ['icd' => 'E53.8', 'hastalikadi' => 'B grubu vitamin eksikliği, diğer'],
        ['icd' => 'E55.9', 'hastalikadi' => 'Vitamin D eksikliği, tanımlanmamış'],
        ['icd' => 'E66.0', 'hastalikadi' => 'Obezite, aşırı kalori alımı ile'],
        ['icd' => 'E66.9', 'hastalikadi' => 'Obezite, tanımlanmamış'],
        ['icd' => 'E78.0', 'hastalikadi' => 'Saf hiperkolesterolemi'],
        ['icd' => 'E78.1', 'hastalikadi' => 'Saf hiperglyceridemi'],
        ['icd' => 'E78.2', 'hastalikadi' => 'Karma hiperlipidemi'],
        ['icd' => 'E78.4', 'hastalikadi' => 'Diğer hiperlipidemi'],
        ['icd' => 'E78.5', 'hastalikadi' => 'Hiperlipidemi, tanımlanmamış'],
        ['icd' => 'E83.5', 'hastalikadi' => 'Bozuk kalsiyum metabolizması'],
        ['icd' => 'E86', 'hastalikadi' => 'Volüm deplesyonu'],
        ['icd' => 'E87.0', 'hastalikadi' => 'Hiperozmolite ve hipernatremi'],
        ['icd' => 'E87.1', 'hastalikadi' => 'Hiponatremi'],
        ['icd' => 'E87.5', 'hastalikadi' => 'Hiperkalemi'],
        ['icd' => 'E87.6', 'hastalikadi' => 'Hipokalemi'],

        // --- Solunum (J) ---
        ['icd' => 'J00', 'hastalikadi' => 'Akut nazofarenjit'],
        ['icd' => 'J01.9', 'hastalikadi' => 'Akut sinüzit, tanımlanmamış'],
        ['icd' => 'J02.9', 'hastalikadi' => 'Akut farenjit, tanımlanmamış'],
        ['icd' => 'J03.9', 'hastalikadi' => 'Akut tonsillit, tanımlanmamış'],
        ['icd' => 'J04.0', 'hastalikadi' => 'Akut larenjit'],
        ['icd' => 'J06.9', 'hastalikadi' => 'Akut üst solunum yolu enfeksiyonu, tanımlanmamış'],
        ['icd' => 'J13', 'hastalikadi' => 'Pnömoni, Streptococcus pneumoniae'],
        ['icd' => 'J15.9', 'hastalikadi' => 'Bakteriyel pnömoni, tanımlanmamış'],
        ['icd' => 'J18.1', 'hastalikadi' => 'Lob pnömoni, tanımlanmamış'],
        ['icd' => 'J18.9', 'hastalikadi' => 'Pnömoni, tanımlanmamış'],
        ['icd' => 'J20.9', 'hastalikadi' => 'Akut bronşit, tanımlanmamış'],
        ['icd' => 'J21.9', 'hastalikadi' => 'Akut bronşiolit, tanımlanmamış'],
        ['icd' => 'J22', 'hastalikadi' => 'Akut alt solunum yolu enfeksiyonu, tanımlanmamış'],
        ['icd' => 'J40', 'hastalikadi' => 'Bronşit, tanımlanmamış'],
        ['icd' => 'J41.0', 'hastalikadi' => 'Basit kronik bronşit'],
        ['icd' => 'J42', 'hastalikadi' => 'Kronik bronşit, tanımlanmamış'],
        ['icd' => 'J43.9', 'hastalikadi' => 'Amfizem, tanımlanmamış'],
        ['icd' => 'J44.0', 'hastalikadi' => 'KOAH, akut alt solunum yolu enfeksiyonu ile'],
        ['icd' => 'J44.1', 'hastalikadi' => 'KOAH, akut alevlenme ile'],
        ['icd' => 'J44.9', 'hastalikadi' => 'Kronik obstrüktif akciğer hastalığı, tanımlanmamış'],
        ['icd' => 'J45.9', 'hastalikadi' => 'Astım, tanımlanmamış'],
        ['icd' => 'J47.0', 'hastalikadi' => 'Bronşektazi'],
        ['icd' => 'J69.0', 'hastalikadi' => 'Aspirasyon pnömoni'],
        ['icd' => 'J84.9', 'hastalikadi' => 'İnterstisyel pulmoner hastalık, tanımlanmamış'],
        ['icd' => 'J90', 'hastalikadi' => 'Plevral efüzyon, açıklanmamış'],
        ['icd' => 'J96.00', 'hastalikadi' => 'Akut solunum yetmezliği'],
        ['icd' => 'J96.10', 'hastalikadi' => 'Kronik solunum yetmezliği'],

        // --- Genitoüriner (N) ---
        ['icd' => 'N17.9', 'hastalikadi' => 'Akut böbrek yetmezliği, tanımlanmamış'],
        ['icd' => 'N18.1', 'hastalikadi' => 'Kronik böbrek hastalığı, evre 1'],
        ['icd' => 'N18.2', 'hastalikadi' => 'Kronik böbrek hastalığı, evre 2'],
        ['icd' => 'N18.3', 'hastalikadi' => 'Kronik böbrek hastalığı, evre 3'],
        ['icd' => 'N18.4', 'hastalikadi' => 'Kronik böbrek hastalığı, evre 4'],
        ['icd' => 'N18.5', 'hastalikadi' => 'Kronik böbrek hastalığı, evre 5'],
        ['icd' => 'N18.6', 'hastalikadi' => 'Son dönem böbrek hastalığı'],
        ['icd' => 'N18.9', 'hastalikadi' => 'Kronik böbrek hastalığı, tanımlanmamış'],
        ['icd' => 'N20.0', 'hastalikadi' => 'Böbrek taşı'],
        ['icd' => 'N20.1', 'hastalikadi' => 'Üreter taşı'],
        ['icd' => 'N25.9', 'hastalikadi' => 'Bozulmuş renal-tübüler fonksiyon, tanımlanmamış'],
        ['icd' => 'N30.0', 'hastalikadi' => 'Akut sistit'],
        ['icd' => 'N30.1', 'hastalikadi' => 'İnterstisyel sistit (kronik)'],
        ['icd' => 'N31.9', 'hastalikadi' => 'Nörojen mesane, tanımlanmamış'],
        ['icd' => 'N35.9', 'hastalikadi' => 'Üretra striktürü, tanımlanmamış'],
        ['icd' => 'N36.9', 'hastalikadi' => 'Üriner sistem hastalığı, tanımlanmamış'],
        ['icd' => 'N39.0', 'hastalikadi' => 'Üriner sistem enfeksiyonu, yeri tanımlanmamış'],
        ['icd' => 'N40', 'hastalikadi' => 'Hiperplazi, prostat'],
        ['icd' => 'N81.1', 'hastalikadi' => 'Sistosel'],
        ['icd' => 'N81.3', 'hastalikadi' => 'Rektosel'],
        ['icd' => 'N81.4', 'hastalikadi' => 'Perineal prolapsus'],
        ['icd' => 'N81.9', 'hastalikadi' => 'Pelvik organ prolapsusu, tanımlanmamış'],
        ['icd' => 'N13.9', 'hastalikadi' => 'Obstrüktif ve reflü üropati, tanımlanmamış'],

        // --- Kas-iskelet / yaralanma (M, S) ---
        ['icd' => 'M16.0', 'hastalikadi' => 'Primer koksartroz, bilateral'],
        ['icd' => 'M16.9', 'hastalikadi' => 'Koksartroz, tanımlanmamış'],
        ['icd' => 'M17.0', 'hastalikadi' => 'Primer gonartroz, bilateral'],
        ['icd' => 'M17.9', 'hastalikadi' => 'Gonartroz, tanımlanmamış'],
        ['icd' => 'M19.9', 'hastalikadi' => 'Artroz, tanımlanmamış'],
        ['icd' => 'M47.9', 'hastalikadi' => 'Spondiloz, tanımlanmamış'],
        ['icd' => 'M48.0', 'hastalikadi' => 'Spinal stenoz'],
        ['icd' => 'M51.1', 'hastalikadi' => 'Lomber disk bozukluğu, radikülopati ile'],
        ['icd' => 'M54.2', 'hastalikadi' => 'Servikalgiya'],
        ['icd' => 'M54.5', 'hastalikadi' => 'Lombaağrı'],
        ['icd' => 'M54.9', 'hastalikadi' => 'Dorsalgiya, tanımlanmamış'],
        ['icd' => 'M62.81', 'hastalikadi' => 'Kas zayıflığı (genelize)'],
        ['icd' => 'M79.1', 'hastalikadi' => 'Miyalji'],
        ['icd' => 'M79.3', 'hastalikadi' => 'Siyatika'],
        ['icd' => 'M80.0', 'hastalikadi' => 'Postmenopozal osteoporoz, patolojik kırık ile'],
        ['icd' => 'M81.0', 'hastalikadi' => 'Postmenopozal osteoporoz'],
        ['icd' => 'M81.9', 'hastalikadi' => 'Osteoporoz, tanımlanmamış'],
        ['icd' => 'S22.0', 'hastalikadi' => 'Torakal vertebra kırığı'],
        ['icd' => 'S32.0', 'hastalikadi' => 'Lumbar vertebra kırığı'],
        ['icd' => 'S42.0', 'hastalikadi' => 'Klavikula kırığı'],
        ['icd' => 'S52.5', 'hastalikadi' => 'Radius alt uç kırığı'],
        ['icd' => 'S72.0', 'hastalikadi' => 'Femur boyun kırığı'],
        ['icd' => 'S72.1', 'hastalikadi' => 'Pertrokanterik kırık'],
        ['icd' => 'S93.4', 'hastalikadi' => 'Ayak bileği burkulması ve distorsiyonu'],

        // --- Sindirim (K) ---
        ['icd' => 'K21.0', 'hastalikadi' => 'Gastro-özofageal reflü hastalığı, özofajit ile'],
        ['icd' => 'K21.9', 'hastalikadi' => 'Gastro-özofageal reflü hastalığı, özofajit olmaksızın'],
        ['icd' => 'K25.9', 'hastalikadi' => 'Gastrik ülser, tanımlanmamış'],
        ['icd' => 'K26.9', 'hastalikadi' => 'Duodenal ülser, tanımlanmamış'],
        ['icd' => 'K27.9', 'hastalikadi' => 'Peptik ülser, yeri tanımlanmamış'],
        ['icd' => 'K29.5', 'hastalikadi' => 'Gastrit ve duodenit, tanımlanmamış'],
        ['icd' => 'K30', 'hastalikadi' => 'Fonksiyonel dispepsi'],
        ['icd' => 'K52.9', 'hastalikadi' => 'Gastroenterit ve kolit, enfektif olmayan'],
        ['icd' => 'K56.6', 'hastalikadi' => 'Diğer ve tanımlanmamış intestinal tıkanıklık'],
        ['icd' => 'K57.3', 'hastalikadi' => 'Diyvertiküler hastalık, perforasyon veya apse olmadan'],
        ['icd' => 'K59.0', 'hastalikadi' => 'Kabızlık'],
        ['icd' => 'K59.2', 'hastalikadi' => 'Hipermotilite sendromu'],
        ['icd' => 'K70.30', 'hastalikadi' => 'Alkolik karaciğer hastalığı, tanımlanmamış'],
        ['icd' => 'K74.6', 'hastalikadi' => 'Siroz ve karaciğer fibrozisi, tanımlanmamış'],
        ['icd' => 'K92.2', 'hastalikadi' => 'Gastrointestinal hemoraji, tanımlanmamış'],

        // --- Onkoloji (C) ---
        ['icd' => 'C18.9', 'hastalikadi' => 'Maligan neoplazm, kolon, tanımlanmamış'],
        ['icd' => 'C20', 'hastalikadi' => 'Maligan neoplazm, rektum'],
        ['icd' => 'C25.9', 'hastalikadi' => 'Maligan neoplazm, pankreas, tanımlanmamış'],
        ['icd' => 'C34.9', 'hastalikadi' => 'Maligan neoplazm, bronş veya akciğer, tanımlanmamış'],
        ['icd' => 'C50.9', 'hastalikadi' => 'Maligan neoplazm, meme, tanımlanmamış'],
        ['icd' => 'C61', 'hastalikadi' => 'Maligan neoplazm, prostat'],
        ['icd' => 'C67.9', 'hastalikadi' => 'Maligan neoplazm, mesane, tanımlanmamış'],
        ['icd' => 'C71.9', 'hastalikadi' => 'Maligan neoplazm, beyin, tanımlanmamış'],
        ['icd' => 'C79.9', 'hastalikadi' => 'İkincil malign neoplazm, yeri belirtilmemiş'],
        ['icd' => 'C80.0', 'hastalikadi' => 'Maligan neoplazm, birincil yeri bilinmiyor'],

        // --- Z faktörleri ---
        ['icd' => 'Z00.0', 'hastalikadi' => 'Genel tıbbi muayene'],
        ['icd' => 'Z43.0', 'hastalikadi' => 'Trizom bakımı'],
        ['icd' => 'Z43.1', 'hastalikadi' => 'Kolostomi bakımı'],
        ['icd' => 'Z43.3', 'hastalikadi' => 'İleostomi bakımı'],
        ['icd' => 'Z46.6', 'hastalikadi' => 'Üriner kateter bakımı'],
        ['icd' => 'Z46.8', 'hastalikadi' => 'Diğer belirtilmiş cihazların uygulanması ve bakımı'],
        ['icd' => 'Z51.5', 'hastalikadi' => 'Palyatif bakım'],
        ['icd' => 'Z95.1', 'hastalikadi' => 'Aortokoroner baypas greft varlığı'],
        ['icd' => 'Z95.5', 'hastalikadi' => 'Kalp kapak protezi ve greft varlığı'],
        ['icd' => 'Z96.1', 'hastalikadi' => 'Kalp kapak protezi varlığı'],
        ['icd' => 'Z99.0', 'hastalikadi' => 'Bağımlılık, invaziv mekanik ventilatör'],
        ['icd' => 'Z99.1', 'hastalikadi' => 'Bağımlılık, kalp-akciğer makinesi'],
        ['icd' => 'Z99.2', 'hastalikadi' => 'Bağımlılık, renal diyaliz'],
        ['icd' => 'Z99.3', 'hastalikadi' => 'Bağımlılık, kronik oksijen tedavisi'],
        ['icd' => 'Z99.8', 'hastalikadi' => 'Bağımlılık, diğer destekleyici önlemler'],

        // --- Enfeksiyon (A, B) ---
        ['icd' => 'A09', 'hastalikadi' => 'Diyare ve gastroenterit, enfeksiyöz etken varsayımı'],
        ['icd' => 'A41.9', 'hastalikadi' => 'Sepsis, tanımlanmamış'],
        ['icd' => 'A49.9', 'hastalikadi' => 'Bakteriyel enfeksiyon, tanımlanmamış'],
        ['icd' => 'B02.9', 'hastalikadi' => 'Zona, komplikasyonsuz'],
        ['icd' => 'B37.9', 'hastalikadi' => 'Kandidiyazis, tanımlanmamış'],

        // --- Deri (L) ---
        ['icd' => 'L03.9', 'hastalikadi' => 'Selülit, tanımlanmamış'],
        ['icd' => 'L30.9', 'hastalikadi' => 'Dermatit, tanımlanmamış'],
        ['icd' => 'L89.0', 'hastalikadi' => 'Basınç ülseri, evre I'],
        ['icd' => 'L89.1', 'hastalikadi' => 'Basınç ülseri, evre II'],
        ['icd' => 'L89.2', 'hastalikadi' => 'Basınç ülseri, evre III'],
        ['icd' => 'L89.3', 'hastalikadi' => 'Basınç ülseri, evre IV'],
        ['icd' => 'L89.9', 'hastalikadi' => 'Basınç ülseri, tanımlanmamış'],
        ['icd' => 'L97', 'hastalikadi' => 'Ayak ülseri, diyabetes mellitus dışı'],

        // --- Semptomlar (R) ---
        ['icd' => 'R05', 'hastalikadi' => 'Öksürük'],
        ['icd' => 'R06.0', 'hastalikadi' => 'Dispne'],
        ['icd' => 'R10.4', 'hastalikadi' => 'Diğer ve tanımlanmamış karın ağrısı'],
        ['icd' => 'R11', 'hastalikadi' => 'Bulantı ve kusma'],
        ['icd' => 'R26.2', 'hastalikadi' => 'Hasta yürüyemiyor'],
        ['icd' => 'R50.9', 'hastalikadi' => 'Ateş, tanımlanmamış'],
        ['icd' => 'R52.9', 'hastalikadi' => 'Ağrı, tanımlanmamış'],
        ['icd' => 'R55', 'hastalikadi' => 'Senkop ve kollaps'],

        // --- Komplikasyon / cihaz (T) ---
        ['icd' => 'T84.0', 'hastalikadi' => 'İç eklem protezi mekanik komplikasyonu'],

        // --- Kan (D) ---
        ['icd' => 'D50.9', 'hastalikadi' => 'Demir eksikliği anemisi, tanımlanmamış'],
        ['icd' => 'D51.9', 'hastalikadi' => 'Vitamin B12 eksikliği anemisi, tanımlanmamış'],
        ['icd' => 'D64.9', 'hastalikadi' => 'Anemi, tanımlanmamış'],
    ];
}
