<?php
declare(strict_types=1);

/**
 * ESH — Uygulama modül kayıt defteri
 *
 * Tek doğruluk kaynağı: modüller, controller/action rotaları, isteğe bağlı modül kapısı.
 * Yeniden üretim: php tools/build_app_modules_registry.php
 *
 * İlişkili dosyalar:
 *   config/app-settings.defaults.json — toggleable modül açık/kapalı varsayılanları
 *   public/assets/data/app-settings.json — panelden kaydedilen runtime değerler
 *
 * Alanlar:
 *   routes          — permission katalogu: controller => action listesi (tüm rota)
 *   controllers     — yalnız toggleable modüllerde: kapı kapsamı (tüm controller)
 *   actions         — yalnız toggleable modüllerde: kısmi kapı (belirli action)
 *   toggleable      — false ise ayar panelinde görünmez ve index.php kapısı uygulanmaz
 *
 * @return array<string, array{
 *   key: string,
 *   label: string,
 *   description: string,
 *   group: 'core'|'site'|'admin'|'auth'|'public',
 *   default: bool,
 *   toggleable: bool,
 *   routes: array<string, list<string>>,
 *   controllers?: list<string>,
 *   actions?: list<string>
 * }>
 */
return [
    'dashboard' => [
        'key' => 'dashboard',
        'label' => 'Ana panel',
        'description' => 'Dashboard, takvim, günlük plan ve rota ekranları.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Dashboard' => [
                'admin',
                'calendarMonth',
                'dailyPlanMernisScan',
                'getDailyEvents',
                'getTomTomMatrixData',
                'index',
                'planla',
                'showRoute',
                'showRouteRows',
                'tcLookupAjax',
                'tomtomGeocodeAjax',
                'tomtomMapKeyAjax',
                'tomtomRouteAjax',
                'geocodeAjax',
                'mapConfigAjax',
                'routeAjax',
            ],
        ],
    ],
    'modern_frontend' => [
        'key' => 'modern_frontend',
        'label' => 'Modern frontend pilot',
        'description' => 'Vue 3 dashboard / plan özeti — oturum tabanlı JSON.',
        'group' => 'core',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'ModernFrontend' => [
                'pilotData',
            ],
        ],
        'controllers' => [
            'ModernFrontend',
        ],
    ],
    'patient' => [
        'key' => 'patient',
        'label' => 'Hasta yönetimi',
        'description' => 'Hasta listeleri, kayıt, düzenleme, Barthel, pansuman fotoğrafı ve adres AJAX.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Patient' => [
                'barthel',
                'bedit',
                'braden',
                'bulkDiedScan',
                'bview',
                'changeKurum',
                'changeactive',
                'checkTC',
                'deleteBraden',
                'deleteHarizmi',
                'deleteItaki',
                'deleteBarthel',
                'deleteMna',
                'deleteNote',
                'deletePatientPhoto',
                'deleteWoundPhoto',
                'deletedToWaiting',
                'deletedied',
                'deletewaiting',
                'died',
                'edit',
                'firstSave',
                'fsave',
                'harizmi',
                'ilkkayit',
                'itaki',
                'listactive',
                'listaraf',
                'listdeleted',
                'listdied',
                'listpassive',
                'listwaiting',
                'mna',
                'passiveToWaiting',
                'prepareNotes',
                'randevu_yogunluk_kontrol',
                'resolvePatientCoords',
                'saveBarthel',
                'saveBraden',
                'saveHarizmi',
                'saveItaki',
                'saveMna',
                'scan',
                'scanWaiting',
                'store',
                'storeKurum',
                'toggleClinicalFlag',
                'unified',
                'unifiedPdfData',
                'unifiedRows',
                'updateNotes',
                'uploadPatientPhoto',
                'uploadWoundPhoto',
                'view',
                'waitingForm',
                'wounds',
            ],
            'Address' => [
                'getSubAddresses',
                'saveKapino',
                'saveSokak',
            ],
        ],
    ],
    'visit' => [
        'key' => 'visit',
        'label' => 'Ev ziyareti (izlem)',
        'description' => 'Tamamlanan izlemler, EK-3 konsültasyon ve izlem CRUD.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Visit' => [
                'checkVisitSameDay',
                'create',
                'delete',
                'edit',
                'ek3Consult',
                'ek3Document',
                'ek3SavePrint',
                'history',
                'historyRows',
                'index',
                'indexPdfData',
                'indexRows',
                'missed',
                'missedRows',
                'store',
                'update',
            ],
        ],
    ],
    'planned_visit' => [
        'key' => 'planned_visit',
        'label' => 'Planlanan ziyaret',
        'description' => 'Planlı ev ziyaretleri, pasif hasta plan temizliği.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'PlannedVisit' => [
                'checkPlanSameSlot',
                'create',
                'delete',
                'deletePassivePendingAfterBulk',
                'deletePassivePendingBulk',
                'edit',
                'index',
                'indexPdfData',
                'indexRows',
                'markPassivePendingMissedBulk',
                'passivePendingPlans',
                'passivePendingPlansRows',
                'patient',
                'patientRows',
                'plan_yogunluk_kontrol',
                'store',
                'update',
            ],
        ],
    ],
    'pansuman' => [
        'key' => 'pansuman',
        'label' => 'Pansuman planı',
        'description' => 'Hasta pansuman günleri listesi ve kayıt.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Pansuman' => [
                'index',
                'indexRows',
                'saveDays',
            ],
        ],
    ],
    'planning' => [
        'key' => 'planning',
        'label' => 'Günlük planlama',
        'description' => 'Günlük ziyaret plan tablosu ve skor kaydı.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Planning' => [
                'index',
                'indexRows',
                'save',
                'table',
            ],
        ],
    ],
    'stats' => [
        'key' => 'stats',
        'label' => 'İstatistikler',
        'description' => 'Rapor hub, KPI kartları ve çapraz tablo istatistikleri.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Stats' => [
                'adresFilterOptions',
                'adresPatientFilter',
                'adresPatientFilterRows',
                'ageGenderBands',
                'ageSummary',
                'anthroCoverage',
                'ayMovement',
                'aylikTekIzlemliler',
                'aylikTekIzlemlilerRows',
                'bagimlilikDist',
                'barthel',
                'birIzlemliler',
                'birIzlemlilerRows',
                'birthdays',
                'birthdaysRows',
                'bmiVki',
                'braden',
                'charts',
                'chronologyIssues',
                'clinicalDecisionSupport',
                'clinicalProfile',
                'dataHealth',
                'dataHealthContent',
                'dataHealthPatients',
                'dataHealthPatientsRows',
                'demographicCompleteness',
                'eraporHastaUyum',
                'eraporHastaUyumContent',
                'eraporHastaUyumList',
                'eraporHastaUyumListRows',
                'eraporHastaUyumMetrics',
                'eraporList',
                'eraporListRows',
                'exitReasons',
                'fieldCoverage',
                'fieldCoveragePatients',
                'fieldCoveragePatientsRows',
                'followKpi',
                'geoDistribution',
                'guvenceAgeBands',
                'guvenceDist',
                'harizmi',
                'hastalik',
                'hastalikCountDist',
                'hastalikPatients',
                'hastalikPatientsRows',
                'index',
                'itaki',
                'kayitKohortAge',
                'kayitMonths',
                'kayitTenure',
                'mna',
                'monthlyFollowFreq',
                'monthlyPool',
                'operationsPulse',
                'overview',
                'pansumanProfile',
                'passiveReasons',
                'patientStatus',
                'plannedVisitStats',
                'randevuKayitGap',
                'randevuTakvim',
                'regionalPerformance',
                'reportPdfData',
                'sondaChanges',
                'sondaChangesRows',
                'specialDevices',
                'specialDevicesRows',
                'stokOzet',
                'supplyReports',
                'supplyReportsRows',
                'supplyStokPanel',
                'topVisits',
                'topVisitsRows',
                'visitConsultationMonthly',
                'visitPersonnel',
                'visitProcedures',
                'visitStats',
                'waitingPoolProfile',
                'workload',
                'workloadRows',
                'xTab_ageMonthVisited',
                'xTab_bagimlilikAge',
                'xTab_bagimlilikVisitYear',
                'xTab_barthelAge',
                'xTab_bmiAge',
                'xTab_bmiBagimlilik',
                'xTab_bradenRiskAge',
                'xTab_branchMonthKons',
                'xTab_branchZamanKons',
                'xTab_deviceCountAge',
                'xTab_exitMonthIlce',
                'xTab_exitReasonTenure',
                'xTab_exitReasonYear',
                'xTab_guvenceBagimlilik',
                'xTab_guvenceVisitGap',
                'xTab_harizmiRiskAge',
                'xTab_hastalikCountAge',
                'xTab_ilceAge',
                'xTab_ilcePlanStatus',
                'xTab_ilceVisitDone',
                'xTab_itakiRiskAge',
                'xTab_kayitYearAge',
                'xTab_mnaStatusAge',
                'xTab_monthAttendKons',
                'xTab_monthPlanPriority',
                'xTab_monthPlanStatus',
                'xTab_monthPlanZaman',
                'xTab_monthVisitDone',
                'xTab_monthVisitZaman',
                'xTab_pansumanVisitGap',
                'xTab_personnelMonth',
                'xTab_procedureMonth',
                'xTab_tenureVisitCount',
                'xTab_vehicleMonth',
                'yearlyFollow',
            ],
        ],
    ],
    'user' => [
        'key' => 'user',
        'label' => 'Kullanıcı ve profil',
        'description' => 'Profil, istatistik, fotoğraf ve yönetici kullanıcı CRUD.',
        'group' => 'core',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'User' => [
                'adminEdit',
                'changeKurum',
                'create',
                'cropsave',
                'delete',
                'edit',
                'image',
                'index',
                'list',
                'listRows',
                'profileStatsContent',
                'removephoto',
                'stats',
                'statsDetail',
                'store',
                'storeKurum',
                'update',
                'upload',
            ],
        ],
    ],
    'auth' => [
        'key' => 'auth',
        'label' => 'Oturum açma',
        'description' => 'Kullanıcı adı/parola ile giriş ve çıkış.',
        'group' => 'auth',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Auth' => [
                'doLogin',
                'login',
                'logout',
            ],
        ],
    ],
    'eimza_login' => [
        'key' => 'eimza_login',
        'label' => 'E-imza ile giriş',
        'description' => 'Oturum açma ekranında e-imza challenge ve giriş uç noktaları.',
        'group' => 'auth',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Auth' => [
                'eimzaChallenge',
                'eimzaLogin',
            ],
        ],
        'controllers' => [
                'Auth',
            ],
        'actions' => [
                'eimzaChallenge',
                'eimzaLogin',
            ],
    ],
    'public_hastaarama' => [
        'key' => 'public_hastaarama',
        'label' => 'Hasta TC sorgulama (misafir)',
        'description' => 'Oturumsuz kayıtlı hasta TC arama (OperationalSettings ile ayrıca kapatılabilir).',
        'group' => 'public',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'PublicHastaarama' => [
                'index',
                'sonuc',
            ],
        ],
    ],
    'patient_portal' => [
        'key' => 'patient_portal',
        'label' => 'Hasta / bakım veren portalı',
        'description' => 'TC + telefon ile oturum; plan, ziyaret özeti ve SMS onayı.',
        'group' => 'public',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'PatientPortal' => [
                'doLogin',
                'index',
                'login',
                'logout',
                'updateSmsConsent',
            ],
        ],
    ],
    'erapor' => [
        'key' => 'erapor',
        'label' => 'e-Rapor',
        'description' => 'e-Rapor listesi, oluşturma ve hasta havuzu işlemleri.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Erapor' => [
                'create',
                'delete',
                'edit',
                'index',
                'indexPdfData',
                'indexRows',
                'markAsProcessed',
                'store',
                'tcGroupRows',
                'tcLookupAjax',
                'view',
            ],
        ],
        'controllers' => [
                'Erapor',
            ],
    ],
    'randevu' => [
        'key' => 'randevu',
        'label' => 'Branş randevu takvimi',
        'description' => 'Branş konsültasyon randevu takvimi ve kayıtları.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Randevu' => [
                'bransKota',
                'dayAppointmentRows',
                'delete',
                'index',
                'patientSearch',
                'store',
                'updateGeldi',
            ],
        ],
        'controllers' => [
                'Randevu',
            ],
    ],
    'uhds' => [
        'key' => 'uhds',
        'label' => 'Uhds',
        'description' => 'Uhds randevu takvimi.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Uhds' => [
                'completeSession',
                'dayAppointmentRows',
                'delete',
                'index',
                'patientJoinLink',
                'patientSearch',
                'patientVideo',
                'patientVideoConfig',
                'store',
                'updateGeldi',
                'video',
                'videoConfig',
            ],
        ],
        'controllers' => [
                'Uhds',
            ],
    ],
    'hasta_ilac_rapor' => [
        'key' => 'hasta_ilac_rapor',
        'label' => 'İlaç / tanı raporu',
        'description' => 'Hasta kartından ilaç ve tanı raporu modülü.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'HastaIlacRapor' => [
                'delete',
                'deleteIlac',
                'ilacRows',
                'index',
                'raporRows',
                'store',
                'storeIlac',
                'updateIlac',
            ],
        ],
        'controllers' => [
                'HastaIlacRapor',
            ],
    ],
    'ilac_rehber' => [
        'key' => 'ilac_rehber',
        'label' => 'İlaç rehberi (etken)',
        'description' => 'Rehber snapshot: etken / ilaç arama; veri özeti süper yönetici menüsünde.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'IlacRehber' => [
                'about',
                'etken',
                'etkenAjax',
                'ilacAjax',
                'index',
                'migration',
                'scrapeCancel',
                'scrapeStart',
                'scrapeStatus',
                'search',
                'statsAjax',
            ],
        ],
        'controllers' => [
                'IlacRehber',
            ],
    ],
    'mesajlasma' => [
        'key' => 'mesajlasma',
        'label' => 'Mesajlaşma',
        'description' => 'Birebir mesaj, hasta konuşmaları ve sistem duyuruları.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Mesaj' => [
                'broadcast',
                'broadcastSend',
                'compose',
                'inboxRows',
                'index',
                'markRead',
                'moveToTrash',
                'patientThread',
                'poll',
                'pollThread',
                'purge',
                'restore',
                'send',
                'sent',
                'startDm',
                'thread',
                'threadRows',
                'trash',
                'usersForDm',
            ],
        ],
        'controllers' => [
                'Mesaj',
            ],
    ],
    'sms_bildirim' => [
        'key' => 'sms_bildirim',
        'label' => 'SMS bildirimleri',
        'description' => 'Toplu SMS, şablonlar, günlük plan bildirimi ve gönderim geçmişi.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Sms' => [
                'compose',
                'history',
                'historyDetail',
                'index',
                'previewRecipients',
                'quickFromPatient',
                'saveTemplate',
                'send',
                'templates',
                'testConnection',
            ],
        ],
        'controllers' => [
                'Sms',
            ],
    ],
    'stok' => [
        'key' => 'stok',
        'label' => 'Stok takibi',
        'description' => 'Malzeme, giriş/çıkış/iade, kritik stok ve hasta bazlı tüketim.',
        'group' => 'site',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Stok' => [
                'cikis',
                'cikisStore',
                'giris',
                'girisStore',
                'hareketler',
                'hareketlerExportData',
                'hareketlerRows',
                'hastaLookupAjax',
                'hastaOzet',
                'hastaOzetRows',
                'iade',
                'iadeStore',
                'index',
                'indexExportData',
                'indexRows',
                'kritikStok',
                'kritikStokRows',
                'malzemeCreate',
                'malzemeDelete',
                'malzemeEdit',
                'malzemeList',
                'malzemeListRows',
                'malzemeStore',
                'sayim',
                'sayimStore',
                'siparisExportData',
                'siparisOneri',
            ],
        ],
        'controllers' => [
                'Stok',
            ],
    ],
    'archive' => [
        'key' => 'archive',
        'label' => 'Hasta dosya sistemi',
        'description' => 'Arşiv / hasta dosya sistemi (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Archive' => [
                'index',
                'indexRows',
            ],
        ],
        'controllers' => [
                'Archive',
            ],
    ],
    'ekip' => [
        'key' => 'ekip',
        'label' => 'Ekip planlama sistemi',
        'description' => 'Günlük ekip planlama ve vardiya yönetimi (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Ekip' => [
                'deleteDay',
                'edit',
                'getEkiplerJSON',
                'index',
                'indexRows',
                'saveDaily',
            ],
        ],
        'controllers' => [
                'Ekip',
            ],
    ],
    'adrestanim' => [
        'key' => 'adrestanim',
        'label' => 'Adres tanımları sistemi',
        'description' => 'Mahalle, sokak ve kapı no adres hiyerarşisi (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Adrestanim' => [
                'ajaxDelete',
                'ajaxExternalFill',
                'ajaxGeocodeKapino',
                'ajaxGeocodeKapinoBulk',
                'ajaxList',
                'ajaxSave',
                'index',
            ],
        ],
        'controllers' => [
                'Adrestanim',
            ],
    ],
    'nobet' => [
        'key' => 'nobet',
        'label' => 'Nöbet planı sistemi',
        'description' => 'Nöbet takvimi, izin/istek/tatil ve otomatik dağıtım (yönetim). Personel İzin/Mazeret ekranı modülden bağımsızdır.',
        'group' => 'admin',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Nobet' => [
                'addNobet',
                'deleteIstek',
                'deleteIzin',
                'deleteMineIstek',
                'deleteMineIzin',
                'deleteNobet',
                'deleteTatil',
                'index',
                'mine',
                'mineIstekRows',
                'mineIzinRows',
                'monthlySummary',
                'moveNobet',
                'rebuild',
                'saveIstek',
                'saveIzin',
                'saveMineIstek',
                'saveMineIzin',
                'saveTatil',
                'yearlyStats',
            ],
        ],
        'controllers' => [
                'Nobet',
            ],
        'actions' => [
                'index',
                'monthlySummary',
                'yearlyStats',
                'rebuild',
                'saveIzin',
                'saveIstek',
                'saveTatil',
                'deleteIzin',
                'deleteIstek',
                'deleteTatil',
                'addNobet',
                'moveNobet',
                'deleteNobet',
            ],
    ],
    'harita' => [
        'key' => 'harita',
        'label' => 'Hasta haritası',
        'description' => 'Hasta haritası — çoklu sağlayıcı (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'Harita' => [
                'index',
                'tomtomMapKeyAjax',
                'tomtomRouteAjax',
                'mapConfigAjax',
                'routeAjax',
            ],
        ],
        'controllers' => [
                'Harita',
            ],
    ],
    'adres_koordinat' => [
        'key' => 'adres_koordinat',
        'label' => 'Adres koordinat bulma',
        'description' => 'Adres koordinat eşleme aracı (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => true,
        'routes' => [
            'AdresKoordinat' => [
                'index',
                'processNext',
            ],
        ],
        'controllers' => [
                'AdresKoordinat',
            ],
    ],
    'brans' => [
        'key' => 'brans',
        'label' => 'Branş tanımları',
        'description' => 'Branş listesi, kota ve CRUD (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Brans' => [
                'create',
                'delete',
                'edit',
                'index',
                'indexRows',
                'saveKotas',
                'saveSelection',
                'store',
            ],
        ],
    ],
    'guvence' => [
        'key' => 'guvence',
        'label' => 'Güvence tanımları',
        'description' => 'Güvence türü CRUD (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Guvence' => [
                'create',
                'delete',
                'edit',
                'index',
                'indexRows',
                'store',
            ],
        ],
    ],
    'hastalik' => [
        'key' => 'hastalik',
        'label' => 'Hastalık tanımları',
        'description' => 'ICD / hastalık kataloğu CRUD (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Hastalik' => [
                'create',
                'delete',
                'edit',
                'index',
                'indexRows',
                'pickerExpand',
                'saveSelection',
                'searchAssigned',
                'searchCatalog',
                'store',
                'treeNodes',
            ],
        ],
    ],
    'islem' => [
        'key' => 'islem',
        'label' => 'İşlem tanımları',
        'description' => 'Ev ziyareti işlem kodları CRUD (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Islem' => [
                'create',
                'delete',
                'edit',
                'index',
                'indexRows',
                'saveSelection',
                'store',
            ],
        ],
    ],
    'istek' => [
        'key' => 'istek',
        'label' => 'Personel izin / istek',
        'description' => 'Personel izin ve mazeret istekleri (yönetim listesi).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Istek' => [
                'create',
                'delete',
                'edit',
                'index',
                'indexRows',
                'saveSelection',
                'store',
            ],
        ],
    ],
    'arac' => [
        'key' => 'arac',
        'label' => 'Araç tanımları',
        'description' => 'Saha araç listesi CRUD (yönetim).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Arac' => [
                'create',
                'delete',
                'edit',
                'index',
                'indexRows',
                'store',
            ],
        ],
    ],
    'ilac_listesi' => [
        'key' => 'ilac_listesi',
        'label' => 'TİTCK ilaç listesi yükleme',
        'description' => 'E-Reçete ilaç listesi JSON yükleme (süper yönetici).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'IlacListesi' => [
                'index',
                'upload',
            ],
        ],
    ],
    'db_maintenance' => [
        'key' => 'db_maintenance',
        'label' => 'Veritabanı bakımı',
        'description' => 'Yedekleme, geri yükleme ve optimizasyon (süper yönetici).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'DbMaintenance' => [
                'analyze',
                'analyzeTable',
                'check',
                'checkTable',
                'createBackup',
                'createGroupBackup',
                'createTableBackup',
                'deleteBackup',
                'download',
                'index',
                'optimize',
                'optimizeTable',
                'restoreBackup',
                'restoreTableBackup',
            ],
        ],
    ],
    'audit_log' => [
        'key' => 'audit_log',
        'label' => 'İşlem günlüğü (denetim)',
        'description' => 'KVKK / iç denetim — hasta, izlem, dışa aktarma ve oturum kayıtları.',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'AuditLog' => [
                'index',
                'indexRows',
            ],
        ],
    ],
    'esys_compliance' => [
        'key' => 'esys_compliance',
        'label' => 'ESYS uyum hazırlığı',
        'description' => 'ESYS alan eşlemesi, dosya köprüsü ve referans numaraları.',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'EsysCompliance' => [
                'index',
            ],
            'EsysBridge' => [
                'export',
                'importRefs',
                'index',
                'syncLogRows',
            ],
        ],
        'controllers' => [
            'EsysCompliance',
            'EsysBridge',
        ],
    ],
    'usbs_compliance' => [
        'key' => 'usbs_compliance',
        'label' => 'USBS / e-Nabız uyum hazırlığı',
        'description' => 'USBS alan eşlemesi, izlem bildirimi köprüsü ve referans numaraları.',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'UsbsCompliance' => [
                'index',
            ],
            'UsbsBridge' => [
                'export',
                'importRefs',
                'index',
                'syncLogRows',
            ],
        ],
        'controllers' => [
            'UsbsCompliance',
            'UsbsBridge',
        ],
    ],
    'federation' => [
        'key' => 'federation',
        'label' => 'Federasyon / çok bölgeli SaaS',
        'description' => 'Bölge yönetimi, süper yönetici bölge filtresi ve dosya köprüsü.',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Federation' => [
                'index',
                'setBolgeFilter',
            ],
            'FederationRegion' => [
                'create',
                'delete',
                'edit',
                'index',
                'store',
            ],
            'FederationBridge' => [
                'export',
                'importBundle',
                'index',
                'syncLogRows',
            ],
        ],
        'controllers' => [
            'Federation',
            'FederationRegion',
            'FederationBridge',
        ],
    ],
    'rest_api' => [
        'key' => 'rest_api',
        'label' => 'REST API (v1)',
        'description' => 'Bearer token ile /api/v1/patients, visits, plans JSON uçları.',
        'group' => 'admin',
        'default' => false,
        'toggleable' => true,
        'routes' => [
            'ApiToken' => [
                'index',
                'revoke',
                'store',
            ],
        ],
    ],
    'cdn_check' => [
        'key' => 'cdn_check',
        'label' => 'CDN sürüm denetimi',
        'description' => 'Harici CDN paket sürüm kontrolü (sistem sahibi).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'CdnCheck' => [
                'index',
            ],
        ],
    ],
    'theme' => [
        'key' => 'theme',
        'label' => 'Tema yönetimi',
        'description' => 'Site teması seçimi, renk düzenleyici ve önizleme.',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Theme' => [
                'activate',
                'applySessionPreview',
                'clearSessionPreview',
                'editor',
                'index',
                'indexRows',
                'previewSave',
                'previewShell',
                'saveColors',
                'sessionPreviewState',
            ],
        ],
    ],
    'settings' => [
        'key' => 'settings',
        'label' => 'Uygulama ayarları',
        'description' => 'Modül, harita, planlama ve operasyonel ayar paneli (süper yönetici).',
        'group' => 'admin',
        'default' => true,
        'toggleable' => false,
        'routes' => [
            'Settings' => [
                'index',
                'save',
            ],
        ],
    ],
    'kps_tc_sorgu' => [
        'key' => 'kps_tc_sorgu',
        'label' => 'KPS TC sorgusu',
        'description' => 'Kimlik Paylaşım Sistemi (KPS) ile TC kimlik doğrulama ve nüfus bilgisi sorgusu.',
        'group' => 'admin',
        'default' => false,
        'toggleable' => true,
        'routes' => [
            'Kps' => [
                'deathLookupAjax',
                'lookupAjax',
                'testConnection',
            ],
        ],
        'controllers' => [
                'Kps',
            ],
    ],
];
