-- =============================================================================
-- ESH kurulum seed — Tıp branşları (platform kataloğu)
-- Tablo: `#__branslar` (kaynak: `esh_branslar`) | Satır: 88
-- Kurulum sırasında Installer otomatik çalıştırır.
-- Elle: mysql -u KULLANICI -p VERITABANI < database/seed/seed_esh_branslar.sql
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `#__branslar` (`id`, `kurum_id`, `bransadi`, `hasta_kotasi`) VALUES
('1', '0', 'Acil Tıp', NULL),
('2', '0', 'Adli Tıp', NULL),
('3', '0', 'Ağız, Yüz ve Çene Cerrahisi', NULL),
('4', '0', 'Aile Hekimliği', NULL),
('5', '0', 'Anatomi', NULL),
('6', '0', 'Anesteziyoloji ve Reanimasyon', NULL),
('7', '0', 'Askeri Sağlık Hizmetleri', NULL),
('8', '0', 'Beyin ve Sinir Cerrahisi', NULL),
('9', '0', 'Çocuk Cerrahisi', NULL),
('10', '0', 'Çocuk Sağlığı ve Hastalıkları', NULL),
('11', '0', 'Çocuk ve Ergen Ruh Sağlığı ve Hastalıkları', NULL),
('12', '0', 'Deri ve Zührevi Hastalıkları', NULL),
('13', '0', 'Enfeksiyon Hastalıkları ve Klinik Mikrobiyoloji', NULL),
('14', '0', 'Fiziksel Tıp ve Rehabilitasyon', NULL),
('15', '0', 'Fizyoloji', NULL),
('16', '0', 'Genel Cerrahi', NULL),
('17', '0', 'Göğüs Cerrahisi', NULL),
('18', '0', 'Göğüs Hastalıkları', NULL),
('19', '0', 'Göz Hastalıkları', NULL),
('20', '0', 'Halk Sağlığı', NULL),
('21', '0', 'Hava ve Uzay Hekimliği', NULL),
('22', '0', 'Histoloji ve Embriyoloji', NULL),
('23', '0', 'İç Hastalıkları', NULL),
('24', '0', 'Kadın Hastalıkları ve Doğum', NULL),
('25', '0', 'Kalp ve Damar Cerrahisi', NULL),
('26', '0', 'Kardiyoloji', NULL),
('27', '0', 'Kulak Burun Boğaz Hastalıkları', NULL),
('28', '0', 'Nöroloji', NULL),
('29', '0', 'Nükleer Tıp', NULL),
('30', '0', 'Ortopedi ve Travmatoloji', NULL),
('31', '0', 'Plastik, Rekonstrüktif ve Estetik Cerrahi', NULL),
('32', '0', 'Radyasyon Onkolojisi', NULL),
('33', '0', 'Radyoloji', NULL),
('34', '0', 'Ruh Sağlığı ve Hastalıkları', NULL),
('35', '0', 'Spor Hekimliği', NULL),
('36', '0', 'Sualtı Hekimliği ve Hiperbarik Tıp', NULL),
('37', '0', 'Tıbbi Biyokimya', NULL),
('38', '0', 'Tıbbi Ekoloji ve Hidroklimatoloji', NULL),
('39', '0', 'Tıbbi Farmakoloji', NULL),
('40', '0', 'Tıbbi Genetik', NULL),
('41', '0', 'Tıbbi Mikrobiyoloji', NULL),
('42', '0', 'Tıbbi Patoloji', NULL),
('43', '0', 'Üroloji', NULL),
('44', '0', 'Algoloji', NULL),
('45', '0', 'Askeri Psikiyatri', NULL),
('46', '0', 'Cerrahi Onkoloji', NULL),
('47', '0', 'Çevre Sağlığı', NULL),
('48', '0', 'Çocuk Acil', NULL),
('49', '0', 'Çocuk Endokrinolojisi', NULL),
('50', '0', 'Çocuk Enfeksiyon Hastalıkları', NULL),
('51', '0', 'Çocuk Gastroenterolojisi', NULL),
('52', '0', 'Çocuk Genetik Hastalıkları', NULL),
('53', '0', 'Çocuk Göğüs Hastalıkları', NULL),
('54', '0', 'Çocuk Hematolojisi ve Onkolojisi', NULL),
('55', '0', 'Çocuk İmmünolojisi ve Alerji Hastalıkları', NULL),
('56', '0', 'Çocuk Kalp ve Damar Cerrahisi', NULL),
('57', '0', 'Çocuk Kardiyolojisi', NULL),
('58', '0', 'Çocuk Metabolizma Hastalıkları', NULL),
('59', '0', 'Çocuk Nefrolojisi', NULL),
('60', '0', 'Çocuk Nörolojisi', NULL),
('61', '0', 'Çocuk Radyolojisi', NULL),
('62', '0', 'Çocuk Romatolojisi', NULL),
('63', '0', 'Çocuk Ürolojisi', NULL),
('64', '0', 'Çocuk Yoğun Bakımı', NULL),
('65', '0', 'El Cerrahisi', NULL),
('66', '0', 'Endokrinoloji ve Metabolizma Hastalıkları', NULL),
('67', '0', 'Epidemiyoloji', NULL),
('68', '0', 'Gastroenteroloji', NULL),
('69', '0', 'Gastroenteroloji Cerrahisi', NULL),
('70', '0', 'Geriatri', NULL),
('71', '0', 'Harp Cerrahisi', NULL),
('72', '0', 'Hematoloji', NULL),
('73', '0', 'İmmünoloji ve Alerji Hastalıkları', NULL),
('74', '0', 'İş ve Meslek Hastalıkları', NULL),
('75', '0', 'Jinekolojik Onkoloji Cerrahisi', NULL),
('76', '0', 'Klinik Nörofizyoloji', NULL),
('77', '0', 'Nefroloji', NULL),
('78', '0', 'Neonatoloji', NULL),
('79', '0', 'Perinatoloji', NULL),
('80', '0', 'Romatoloji', NULL),
('81', '0', 'Sitopatoloji', NULL),
('82', '0', 'Temel İmmünoloji', NULL),
('83', '0', 'Tıbbi Mikoloji', NULL),
('84', '0', 'Tıbbi Onkoloji', NULL),
('85', '0', 'Tıbbi Parazitoloji', NULL),
('86', '0', 'Tıbbi Viroloji', NULL),
('87', '0', 'Yoğun Bakım', NULL),
('88', '0', 'Gelişimsel Pediatri', NULL);

SET FOREIGN_KEY_CHECKS = 1;
